### ISSUE TITLE
Does not work with CraftUI tooltips anymore

### ISSUE THREAD

**Issue by Stanzilla** [Jaliborc/BagBrother#1]
See 
![2015-08-02_22-48-40](https://cloud.githubusercontent.com/assets/75278/9027961/e6cf020a-3968-11e5-8762-2c1fb8ad2095.png)

**Comment by Jaliborc** [comment]
Apparently blizzard broke the *tooltip:GetItem* function, and it no longer returns valid information on linking tradeskill window items. Hence bagnon cannot know which item is being shown.

I'm unsure wether I should try to hack around it (and not sure how feasible it would be), as most mods appear to be waiting for a fix.

**Comment by Stanzilla** [comment]
Knowing Blizzard we can probably wait for ages for a fix :/

**Comment by SoJourned** [comment]
A few mods are working around it. Auctioneer, Altoholic
http://jira.norganna.org/browse/LTT-56
http://pastebin.com/FeiYTf3i
https://github.com/Zwixx/altoholic/commit/33566e0078861c3d26749e77cfbae8416d02732a

**Comment by Jaliborc** [comment]
@Stanzilla true that.
@SoJourned nice! Gonna check it out!

**Comment by Jaliborc** [comment]
@SoJourned yeah, they hack it as I expected it to be. I'll be adding this in the end of the week (in middle of nowhere, no decent net connection right now)

**Comment by Jaliborc** [comment]
Fixed
