### ISSUE TITLE
Problem opening bags after pulling in latest changes

### ISSUE THREAD

**Issue by Roelio81** [Jaliborc/BagBrother#29]
**Which software were you running?**
 - Addon version name: BagBrother
 - Client used: Vanilla 1.14.4.51311

**Have you read the changelog?**
Yes

**Please describe the bug.**
When logging in, I get the following LUA error popup (I have enabled them):

**Please describe how to reproduce it.**
After logging in, I can no longer open my bags.
It seems linked to the error log below.
Probably introduced by following commit:
https://github.com/Jaliborc/BagBrother/commit/a72c274f17f3353856ac2602ee03b817036f02f0
The error seems to be linked to Addon.CurrencyLimit

**Any Screenshots?**
If applicable, please add screenshots to help explain your problem.

**Error Logs are Important!**
Message: ...nterface/AddOns/BagBrother/core/features/caching.lua:113: 'for' limit must be a number
Time: Tue Sep 12 19:05:55 2023
Count: 1
Stack: ...nterface/AddOns/BagBrother/core/features/caching.lua:113: 'for' limit must be a number
[string "@Interface/AddOns/BagBrother/core/features/caching.lua"]:113: in function `CURRENCY_TRACKED_CHANGED'
[string "@Interface/AddOns/BagBrother/core/features/caching.lua"]:80: in function `?'
[string "@Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua"]:20: in function <...dOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:18>
[string "@Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua"]:56: in function <...dOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:53>
[string "=[C]"]: ?
[string "@Interface/AddOns/Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...las/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua:119>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:388: in function `UIParentLoadAddOn'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:459: in function `TimeManager_LoadUI'
[string "@Interface_Vanilla/FrameXML/UIParent.lua"]:717: in function <Interface_Vanilla/FrameXML/UIParent.lua:686>

Locals: self = <table> {
 SendSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 ParseItem = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:215
 RegisterMessage = <function> defined @Interface/AddOns/Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Interface/AddOns/Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 isBankFrameOpen = false
 player = <table> {
 }
 SaveBag = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:186
 PLAYER_EQUIPMENT_CHANGED = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:94
 BANK_OPEN = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:124
 SaveEquip = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:211
 SendMessage = <function> defined @Interface/AddOns/Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49
 GUILDBANKBAGSLOTS_CHANGED = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:160
 UnregisterAllEvents = <function> defined @Interface/AddOns/Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 UnregisterSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 VAULT_CLOSE = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:147
 PLAYER_MONEY = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:102
 BANK_CLOSE = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:128
 RegisterEvent = <function> defined @Interface/AddOns/Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterAllMessages = <function> defined @Interface/AddOns/Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 CURRENCY_TRACKED_CHANGED = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:110
 NewModule = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 PLAYER_LEVEL_UP = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:98
 OnEnable = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:20
 BAG_UPDATE = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:88
 RegisterSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 CURRENCY_DISPLAY_UPDATE = <function> defined @Interface/AddOns/B

Message: ...nterface/AddOns/BagBrother/core/features/caching.lua:107: attempt to compare number with nil
Time: Tue Sep 12 19:05:56 2023
Count: 1
Stack: ...nterface/AddOns/BagBrother/core/features/caching.lua:107: attempt to compare number with nil
[string "@Interface/AddOns/BagBrother/core/features/caching.lua"]:107: in function `?'
[string "@Interface/AddOns/Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...las/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...las/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: self = <table> {
 SendSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 ParseItem = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:215
 RegisterMessage = <function> defined @Interface/AddOns/Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Interface/AddOns/Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 isBankFrameOpen = false
 player = <table> {
 }
 SaveBag = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:186
 PLAYER_EQUIPMENT_CHANGED = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:94
 BANK_OPEN = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:124
 SaveEquip = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:211
 SendMessage = <function> defined @Interface/AddOns/Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:49
 GUILDBANKBAGSLOTS_CHANGED = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:160
 UnregisterAllEvents = <function> defined @Interface/AddOns/Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 UnregisterSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 VAULT_CLOSE = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:147
 PLAYER_MONEY = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:102
 BANK_CLOSE = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:128
 RegisterEvent = <function> defined @Interface/AddOns/Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterAllMessages = <function> defined @Interface/AddOns/Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 CURRENCY_TRACKED_CHANGED = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:110
 NewModule = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 PLAYER_LEVEL_UP = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:98
 OnEnable = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:20
 BAG_UPDATE = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:88
 RegisterSignal = <function> defined @Interface/AddOns/BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 CURRENCY_DISPLAY_UPDATE = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:106
 GUILD_ROSTER_UPDATE = <function> defined @Interface/AddOns/BagBrother/core/features/caching.lua:156
 UnregisterEvent = <function> defined @Interface/AddOns/Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 Tag = "BAGNON_"
}
_ = "CURRENCY_DISPLAY_UPDATE"
id = nil
quantity = nil
(*temporary) = <table> {
 tracked = <table> {
 }
}
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"

**Comment by Roelio81** [comment]
Reverting the change in caching.lua and currencyTracker.lua of https://github.com/Jaliborc/BagBrother/commit/a72c274f17f3353856ac2602ee03b817036f02f0 seems to fix the issue for me

**Comment by Kanegasi** [comment]
This error also occurs on retail. The issue is that CURRENCY_DISPLAY_UPDATE does not always have return values. The recent fix to check just the quantity has now caused "index is nil" errors.

Here is the fix:

```Lua
function Cacher:CURRENCY_DISPLAY_UPDATE(_, id, quantity)
	if id and quantity then
		self.player.currency[id] = quantity > 0 and quantity or nil
	end
end
```
